---
- hosts: all
  tasks:
  - name: Debug variables
    vars:
      version: 3.10.10
      basename: Python-{{ version }}
      filename: "{{ basename }}.tar.gz"
      url: https://www.python.org/ftp/python/{{ version }}/{{ filename }}
    block:
      - name: Debug print a message
        debug:
          msg: The URL is {{ url }}
      - name: Debug list of variables
        debug:
          var: "{{ item }}"
        loop:
          - version
          - basename
          - filename